### ISSUE TITLE
HA Connection closed

### ISSUE THREAD

**Issue by dcjona** [marcfager/nspanel-mf#4]
Hi,

First great work!
I try to upload the yaml on esphome after edited the code to fit to my sensor in ha..

As soon as i boot , after wifi connection i got this message.. 

[09:43:36][D][api:098]: Accepted 192.168.100.96
[09:43:36][W][api.connection:083]: Home Assistant 2021.12.10 (192.168.100.96): Connection closed

Previously with another yml , i had no problem.. do you know why ha closed the connection ?

Thanks

**Comment by dcjona** [comment]
it was the api password..

**Comment by marcfager** [comment]
Good that you got it working!

**Comment by dcjona** [comment]
thanks for answer, could i ask you what is the use of the M0 to M7 object on the page light of the hmi? i see that it send component on nextion editor but i don't find the correspdance in the yaml ... thank you

**Comment by marcfager** [comment]
Hi,

The m-objects are touch areas. If you add a button to the screen and click it, you will click beside the object as the calibration is not properly aligned. There was an work-around recently in the HA thread, but I have not yet had time to test and implement it. In order to catch the touches I added separate hotspots that work as buttons instead of just using the pictures.
The m-names themselves are not the essential ones here, if you map the m-components' ID:s towards the yaml file you can see that they are used to catch the light button presses.

The m2-m5 objects are used for navigation left and right. There is no right in the current version, but I will soon post an update with multiple Light-pages that can be enabled and disabled from ESPHome (or HA, if you prefer).

**Comment by dcjona** [comment]
yes i found the pageid and hotspot id just now on the yml ;D
Thanks for answer, amazing job, i'm relooking mine and soon share my work on youtube in french.
i will share your github page and design too...  inspired by you
